package com.promineo.mockdrafts.config;

import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;


@RestController
public class SecurityHomeController {

	@GetMapping("/")
	public String home() {
		return ("<style>\r\n"
				+ "h1 {text-align: center;}\r\n"
				+ "body {text-align: center;}\r\n"
				+ "h1 {\r\n"
				+ "  font-size: 125px;\r\n"
				+ "}"
				
				+ ".buttonLogin {\r\n"
				+ "  display: inline-block;\r\n"
				+ "  border-radius: 50px;\r\n"
				+ "  background-color: #50c878;\r\n"
				+ "  border-color: #ffffff;\r\n"
				+ "  border-size: 50px;\r\n"
				+ "  color: #FFFFFF;\r\n"
				+ "  text-align: center;\r\n"
				+ "  font-size: 28px;\r\n"
				+ "  padding: 20px;\r\n"
				+ "  width: 200px;\r\n"
				+ "  transition: all 0.5s;\r\n"
				+ "  cursor: pointer;\r\n"
				+ "  margin: 5px;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".buttonLogin span {\r\n"
				+ "  cursor: pointer;\r\n"
				+ "  display: inline-block;\r\n"
				+ "  position: relative;\r\n"
				+ "  transition: 0.5s;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".buttonLogin span:after {\r\n"
				+ "  content: '\\00bb';\r\n"
				+ "  position: absolute;\r\n"
				+ "  opacity: 0;\r\n"
				+ "  top: 0;\r\n"
				+ "  right: -20px;\r\n"
				+ "  transition: 0.5s;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".buttonLogin:hover span {\r\n"
				+ "  padding-right: 25px;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".buttonLogin:hover span:after {\r\n"
				+ "  opacity: 1;\r\n"
				+ "  right: 0;\r\n"
				+ "}"
				
				+ ".buttonUser {\r\n"
				+ "  display: inline-block;\r\n"
				+ "  border-radius: 50px;\r\n"
				+ "  background-color: #5099ff;\r\n"
				+ "  border-color: #ffffff;\r\n"
				+ "  border-size: 50px;\r\n"
				+ "  color: #FFFFFF;\r\n"
				+ "  text-align: center;\r\n"
				+ "  font-size: 28px;\r\n"
				+ "  padding: 20px;\r\n"
				+ "  width: 200px;\r\n"
				+ "  transition: all 0.5s;\r\n"
				+ "  cursor: pointer;\r\n"
				+ "  margin: 5px;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".buttonUser span {\r\n"
				+ "  cursor: pointer;\r\n"
				+ "  display: inline-block;\r\n"
				+ "  position: relative;\r\n"
				+ "  transition: 0.5s;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".buttonUser span:after {\r\n"
				+ "  content: '\\00bb';\r\n"
				+ "  position: absolute;\r\n"
				+ "  opacity: 0;\r\n"
				+ "  top: 0;\r\n"
				+ "  right: -20px;\r\n"
				+ "  transition: 0.5s;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".buttonUser:hover span {\r\n"
				+ "  padding-right: 25px;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".buttonUser:hover span:after {\r\n"
				+ "  opacity: 1;\r\n"
				+ "  right: 0;\r\n"
				+ "}"
					
				+ ".buttonAdmin {\r\n"
				+ "  display: inline-block;\r\n"
				+ "  border-radius: 50px;\r\n"
				+ "  background-color: #e1ad21;\r\n"
				+ "  border-color: #ffffff;\r\n"
				+ "  border-size: 50px;\r\n"
				+ "  color: #FFFFFF;\r\n"
				+ "  text-align: center;\r\n"
				+ "  font-size: 28px;\r\n"
				+ "  padding: 20px;\r\n"
				+ "  width: 200px;\r\n"
				+ "  transition: all 0.5s;\r\n"
				+ "  cursor: pointer;\r\n"
				+ "  margin: 5px;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".buttonAdmin span {\r\n"
				+ "  cursor: pointer;\r\n"
				+ "  display: inline-block;\r\n"
				+ "  position: relative;\r\n"
				+ "  transition: 0.5s;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".buttonAdmin span:after {\r\n"
				+ "  content: '\\00bb';\r\n"
				+ "  position: absolute;\r\n"
				+ "  opacity: 0;\r\n"
				+ "  top: 0;\r\n"
				+ "  right: -20px;\r\n"
				+ "  transition: 0.5s;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".buttonAdmin:hover span {\r\n"
				+ "  padding-right: 25px;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".buttonAdmin:hover span:after {\r\n"
				+ "  opacity: 1;\r\n"
				+ "  right: 0;\r\n"
				+ "}"
				
				+ "</style>"
				+ "<h1 style=\"color:white;\">Welcome</h1>" 
				+ "<body> "
				+ "<body style=\"background-color:black;\">"
				+ "<button id =\"loginButton\" class=\"buttonLogin\" > <span>Log In </span></button>"
				+ "<script type=\"text/javascript\">"
				+ "document.getElementById(\"loginButton\").onclick = function () {"
				+ "location.href = \"http://localhost:8080/login?logout\";"
				+ "};"
				+ "</script>"
				+ "<button id =\"userButton\" class=\"buttonUser\" ><span>User</span></button>"
				+ "<script type=\"text/javascript\">"
				+ "document.getElementById(\"userButton\").onclick = function () {"
				+ "location.href = \"http://localhost:8080/user\";"
				+ "};"
				+ "</script>"
				+ "<button id =\"adminButton\" class=\"buttonAdmin\" ><span>Admin</span></button>"
				+ "<script type=\"text/javascript\">"
				+ "document.getElementById(\"adminButton\").onclick = function () {"
				+ "location.href = \"http://localhost:8080/admin\";"
				+ "};"
				+ "</script>"
				+ "</body>");
	}

	@PreAuthorize("hasRole('ROLE_USER')")
	@GetMapping("/user")
	public String user() {
		return ("<style>\r\n"
				+ "h1 {text-align: center;}\r\n"
				+ "body {text-align: center;}\r\n"
				+ "h1 {\r\n"
				+ "  font-size: 125px;\r\n"
				+ "}"
				+ "p {\r\n"
				+ "  font-size: 45px;\r\n"
				+ "}"
				
				+ ".buttonLogin {\r\n"
				+ "  display: inline-block;\r\n"
				+ "  border-radius: 50px;\r\n"
				+ "  background-color: #50c878;\r\n"
				+ "  border-color: #ffffff;\r\n"
				+ "  border-size: 50px;\r\n"
				+ "  color: #FFFFFF;\r\n"
				+ "  text-align: center;\r\n"
				+ "  font-size: 28px;\r\n"
				+ "  padding: 20px;\r\n"
				+ "  width: 200px;\r\n"
				+ "  transition: all 0.5s;\r\n"
				+ "  cursor: pointer;\r\n"
				+ "  margin: 5px;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".buttonLogin span {\r\n"
				+ "  cursor: pointer;\r\n"
				+ "  display: inline-block;\r\n"
				+ "  position: relative;\r\n"
				+ "  transition: 0.5s;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".buttonLogin span:after {\r\n"
				+ "  content: '\\00bb';\r\n"
				+ "  position: absolute;\r\n"
				+ "  opacity: 0;\r\n"
				+ "  top: 0;\r\n"
				+ "  right: -20px;\r\n"
				+ "  transition: 0.5s;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".buttonLogin:hover span {\r\n"
				+ "  padding-right: 25px;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".buttonLogin:hover span:after {\r\n"
				+ "  opacity: 1;\r\n"
				+ "  right: 0;\r\n"
				+ "}"
				
				+ ".buttonLogout {\r\n"
				+ "  display: inline-block;\r\n"
				+ "  border-radius: 50px;\r\n"
				+ "  background-color: #b22222;\r\n"
				+ "  border-color: #ffffff;\r\n"
				+ "  border-size: 50px;\r\n"
				+ "  color: #FFFFFF;\r\n"
				+ "  text-align: center;\r\n"
				+ "  font-size: 28px;\r\n"
				+ "  padding: 20px;\r\n"
				+ "  width: 200px;\r\n"
				+ "  transition: all 0.5s;\r\n"
				+ "  cursor: pointer;\r\n"
				+ "  margin: 5px;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".buttonLogout span {\r\n"
				+ "  cursor: pointer;\r\n"
				+ "  display: inline-block;\r\n"
				+ "  position: relative;\r\n"
				+ "  transition: 0.5s;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".buttonLogout span:after {\r\n"
				+ "  content: '\\00bb';\r\n"
				+ "  position: absolute;\r\n"
				+ "  opacity: 0;\r\n"
				+ "  top: 0;\r\n"
				+ "  right: -20px;\r\n"
				+ "  transition: 0.5s;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".buttonLogout:hover span {\r\n"
				+ "  padding-right: 25px;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".buttonLogout:hover span:after {\r\n"
				+ "  opacity: 1;\r\n"
				+ "  right: 0;\r\n"
				+ "}"
				
				+ ".buttonApi {\r\n"
				+ "  display: inline-block;\r\n"
				+ "  border-radius: 50px;\r\n"
				+ "  background-color: #9c33ff ;\r\n"
				+ "  border-color: #ffffff;\r\n"
				+ "  border-size: 50px;\r\n"
				+ "  color: #FFFFFF;\r\n"
				+ "  text-align: center;\r\n"
				+ "  font-size: 28px;\r\n"
				+ "  padding: 20px;\r\n"
				+ "  width: 200px;\r\n"
				+ "  transition: all 0.5s;\r\n"
				+ "  cursor: pointer;\r\n"
				+ "  margin: 5px;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".buttonApi span {\r\n"
				+ "  cursor: pointer;\r\n"
				+ "  display: inline-block;\r\n"
				+ "  position: relative;\r\n"
				+ "  transition: 0.5s;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".buttonApi span:after {\r\n"
				+ "  content: '\\00bb';\r\n"
				+ "  position: absolute;\r\n"
				+ "  opacity: 0;\r\n"
				+ "  top: 0;\r\n"
				+ "  right: -20px;\r\n"
				+ "  transition: 0.5s;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".buttonApi:hover span {\r\n"
				+ "  padding-right: 25px;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".buttonApi:hover span:after {\r\n"
				+ "  opacity: 1;\r\n"
				+ "  right: 0;\r\n"
				+ "}"
				
				+ ".buttonAdmin {\r\n"
				+ "  display: inline-block;\r\n"
				+ "  border-radius: 50px;\r\n"
				+ "  background-color: #e1ad21;\r\n"
				+ "  border-color: #ffffff;\r\n"
				+ "  border-size: 50px;\r\n"
				+ "  color: #FFFFFF;\r\n"
				+ "  text-align: center;\r\n"
				+ "  font-size: 28px;\r\n"
				+ "  padding: 20px;\r\n"
				+ "  width: 200px;\r\n"
				+ "  transition: all 0.5s;\r\n"
				+ "  cursor: pointer;\r\n"
				+ "  margin: 5px;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".buttonAdmin span {\r\n"
				+ "  cursor: pointer;\r\n"
				+ "  display: inline-block;\r\n"
				+ "  position: relative;\r\n"
				+ "  transition: 0.5s;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".buttonAdmin span:after {\r\n"
				+ "  content: '\\00bb';\r\n"
				+ "  position: absolute;\r\n"
				+ "  opacity: 0;\r\n"
				+ "  top: 0;\r\n"
				+ "  right: -20px;\r\n"
				+ "  transition: 0.5s;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".buttonAdmin:hover span {\r\n"
				+ "  padding-right: 25px;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".buttonAdmin:hover span:after {\r\n"
				+ "  opacity: 1;\r\n"
				+ "  right: 0;\r\n"
				+ "}"
				
				+ "</style>"
				+ "<h1 style=\"color:white;\">Welcome User</h1>" 
				+ "<body> "
				+ "<body style=\"background-color:black;\">"
				+ "<p style=\"color:white;\">"
				+ "You now have </p>"
				+ "<p style=\"color:#5099ff;\">"
				+ "GET </p>"
				+ "<p style=\"color:white;\">"
				+ "Access to the API!! </p> "
				+ "<button id =\"buttonLogin\" class=\"buttonLogin\" ><span>Log In </span></button>"
				+ "<script type=\"text/javascript\">"
				+ "document.getElementById(\"buttonLogin\").onclick = function () {"
				+ "location.href = \"http://localhost:8080/login?logout\";"
				+ "};"
				+ "</script>"
				+ "<button id =\"logoutButton\" class=\"buttonLogout\" ><span>Log Out</span></button>"
				+ "<script type=\"text/javascript\">"
				+ "document.getElementById(\"logoutButton\").onclick = function () {"
				+ "location.href = \"http://localhost:8080/logout\";"
				+ "};"
				+ "</script>"
				+ "<button id =\"apiButton\" class=\"buttonApi\" ><span>API</span></button>"
				+ "<script type=\"text/javascript\">"
				+ "document.getElementById(\"apiButton\").onclick = function () {"
				+ "location.href = \"http://localhost:8080/swagger-ui/index.html\";"
				+ "};"
				+ "</script>"
				+ "<button id =\"adminButton\" class=\"buttonAdmin\" ><span>Admin</span></button>"
				+ "<script type=\"text/javascript\">"
				+ "document.getElementById(\"adminButton\").onclick = function () {"
				+ "location.href = \"http://localhost:8080/admin\";"
				+ "};"
				+ "</script>"
				+ "</body>");
	}
	
	@PreAuthorize("hasRole('ROLE_ADMIN')")
	@GetMapping("/admin")
	public String admin() {
		return ("<style>\r\n"
				+ "h1 {text-align: center;}\r\n"
				+ "body {text-align: center;}\r\n"
				+ "h1 {\r\n"
				+ "  font-size: 125px;\r\n"
				+ "}"
				+ "p {\r\n"
				+ "  font-size: 45px;\r\n"
				+ "}"
				
				+ ".buttonLogout {\r\n"
				+ "  display: inline-block;\r\n"
				+ "  border-radius: 50px;\r\n"
				+ "  background-color: #b22222;\r\n"
				+ "  border-color: #ffffff;\r\n"
				+ "  border-size: 50px;\r\n"
				+ "  color: #FFFFFF;\r\n"
				+ "  text-align: center;\r\n"
				+ "  font-size: 28px;\r\n"
				+ "  padding: 20px;\r\n"
				+ "  width: 200px;\r\n"
				+ "  transition: all 0.5s;\r\n"
				+ "  cursor: pointer;\r\n"
				+ "  margin: 5px;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".buttonLogout span {\r\n"
				+ "  cursor: pointer;\r\n"
				+ "  display: inline-block;\r\n"
				+ "  position: relative;\r\n"
				+ "  transition: 0.5s;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".buttonLogout span:after {\r\n"
				+ "  content: '\\00bb';\r\n"
				+ "  position: absolute;\r\n"
				+ "  opacity: 0;\r\n"
				+ "  top: 0;\r\n"
				+ "  right: -20px;\r\n"
				+ "  transition: 0.5s;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".buttonLogout:hover span {\r\n"
				+ "  padding-right: 25px;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".buttonLogout:hover span:after {\r\n"
				+ "  opacity: 1;\r\n"
				+ "  right: 0;\r\n"
				+ "}"
				
				+ ".buttonApi {\r\n"
				+ "  display: inline-block;\r\n"
				+ "  border-radius: 50px;\r\n"
				+ "  background-color: #9c33ff ;\r\n"
				+ "  border-color: #ffffff;\r\n"
				+ "  border-size: 50px;\r\n"
				+ "  color: #FFFFFF;\r\n"
				+ "  text-align: center;\r\n"
				+ "  font-size: 28px;\r\n"
				+ "  padding: 20px;\r\n"
				+ "  width: 200px;\r\n"
				+ "  transition: all 0.5s;\r\n"
				+ "  cursor: pointer;\r\n"
				+ "  margin: 5px;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".buttonApi span {\r\n"
				+ "  cursor: pointer;\r\n"
				+ "  display: inline-block;\r\n"
				+ "  position: relative;\r\n"
				+ "  transition: 0.5s;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".buttonApi span:after {\r\n"
				+ "  content: '\\00bb';\r\n"
				+ "  position: absolute;\r\n"
				+ "  opacity: 0;\r\n"
				+ "  top: 0;\r\n"
				+ "  right: -20px;\r\n"
				+ "  transition: 0.5s;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".buttonApi:hover span {\r\n"
				+ "  padding-right: 25px;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".buttonApi:hover span:after {\r\n"
				+ "  opacity: 1;\r\n"
				+ "  right: 0;\r\n"
				+ "}"
				
				+ "</style>"
				+ "<h1 style=\"color:white;\">Welcome Admin</h1>" 
				+ "<body> "
				+ "<body style=\"background-color:black;\">"
				+ "<p style=\"color:white;\">"
				+ "You now have </p>"  
				+ "<p style=\"color:#5099ff;\">"
				+ "GET </p>"
				+ "<p style=\"color:#50c878;\">"
				+ "POST </p>"
				+ "<p style=\"color:#e1ad21;\">"
				+ "PUT </p>"
				+ "<p style=\"color:#b22222;\">"
				+ "DELETE </p>"
				+ "<p style=\"color:white;\">"
				+ "Access to the API!! </p> "
				+ "<button id =\"logoutButton\" class=\"buttonLogout\" ><span>Log Out</span></button>"
				+ "<script type=\"text/javascript\">"
				+ "document.getElementById(\"logoutButton\").onclick = function () {"
				+ "location.href = \"http://localhost:8080/logout\";"
				+ "};"
				+ "</script>"
				+ "<button id =\"apiButton\" class=\"buttonApi\" ><span>API</span></button>"
				+ "<script type=\"text/javascript\">"
				+ "document.getElementById(\"apiButton\").onclick = function () {"
				+ "location.href = \"http://localhost:8080/swagger-ui/index.html\";"
				+ "};"
				+ "</script>"
				+ "</body>");
	}
	
}
